### ISSUE TITLE
Document the Evaluatable and EvaluatableFunctionObject concepts

### ISSUE THREAD

**Issue by ldionne** [pfultz2/Fit#44]
The `apply_eval` function documents that it requires `Evaluatable` arguments. I wasn't able to find that concept, what is it? Similarly, the `eval` function requires `EvaluatableFunctionObject`, which does not seem to be documented.

**Comment by pfultz2** [comment]
They really are the same. `Evaluatable` means you can call `eval(f)` and `f` has the requirements of `EvaluatableFunctionObject`. I added `EvaluatableFunctionObject` to the documentation. It is a bit unusual since it has an either-or type definition(ie it is either a `NullaryFunctionObject`, or it is an `UnaryFuntionObject` that accepts the `identity` function as a parameter)

**Comment by ldionne** [comment]
Cool for `EvaluatableFunctionObject`, but shouldn't `Evaluatable` be documented too somehow? I understand that it's a bit simplistic, but for completeness?

**Comment by pfultz2** [comment]
Well, I am thinking of replacing `Evaluatable` with `EvaluatableFunctionObject`. So there will only be one concept instead of two.
