### ISSUE TITLE
differences between partial and decorate

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#64]
I don't see the differences between the two function
```
assert(decorate(f)(x)(g)(xs...) == f(x, g, xs...));

assert(partial(f)(xs...)(ys...) == f(xs..., ys...));
```

**Comment by pfultz2** [comment]
Since `partial` allows for continual partial application, it can mask errors. So `decorate` does partial application internally, but will produce proper error messages.

**Comment by viboes** [comment]
I don't understand yet what errors can be masked and how decorate solves the issue.
This merits some explanations in the documentation

**Comment by pfultz2** [comment]
Say, for instance that `f(x, g, xs...)` would cause a compile error due to substitution failure. Then this will compile:

```cpp
partial(f)(x)(g)(xs...);
```

This is because `f(x, g, xs...)` is not callable. So partial will return another function because perhaps if more parameters are applied the function will be callable. There is no way in C++ to know that more parameters can't be applied. Although I am thinking of adding a `limit` decorator so it can annotate the max limit of parameters, which `partial` and `pipable` can use to avoid this scenario. However, this doesn't help with decorators which has no max limit.

In contrast with decorators this will cause a compile error if `f(x, g, xs...)` is not callable:

```cpp
decorate(f)(x)(g)(xs...);
```

That is because the decorator know that there is no more partial applications, so if `f(x, g, xs...)` is not callable the above simply fails as well.

**Comment by viboes** [comment]
What are `f`, `x`and `xs` in

```
assert(decorate(f)(x)(g)(xs...) == f(x, g, xs...));
```

What is the result of `decorate(f)`? What is his signature?

**Comment by pfultz2** [comment]
> What is the result of decorate(f)?
 
The decorator.

> What is his signature?

Something that takes a value `x`.

**Comment by tzlaine** [comment]
+1000.  The above discussion just proves that this stuff needs to be documented.

**Comment by pfultz2** [comment]
Ok I added some more documentation to the decorate adaptor, plus an example. Hopefully, it makes sense. There's just a long chain of things that happen(ie the decorate adaptor returns a decorator that returns an adaptor that returns a function). I don't know of a better way to explain it. I hope the example makes it clearer.

**Comment by viboes** [comment]
Why the decorator `log_f` operator() must has an additional parameter? Why not let those parameter in the creation of the decorator? Or in other words if you accept one why not a variadic number as in ?

```
assert(3 == log(a, b, c)(sum)(1, 2));
```

**Comment by pfultz2** [comment]
> Why the decorator log_f operator() must has an additional parameter?

I would like to support this in the future. However, the user will need to describe the parameters in some way.

> Why not let those parameter in the creation of the decorator?

Because the way the decorator is invoked, its not possible to distinguish between `log(a, b)(sum)(1, 2)` and `log(a)(sum)(a, 1, 2)`.

> Or in other words if you accept one why not a variadic number as in ?

Depending on how multiple parameters are supported in the future, it may be possible to support variadic arguments by "packing" them.

**Comment by pfultz2** [comment]
> Why the decorator log_f operator() must have an additional parameter? Why not let those parameter in the creation of the decorator? Or in other words if you accept one why not a variadic number as in ?

This is related to issue #151, which would allow decorators to support variadic parameters.

**Comment by pfultz2** [comment]
I am going to close since there is no other pending issue here.

**Comment by viboes** [comment]
Could you point to the changes you did to fix it?

**Comment by pfultz2** [comment]
I have made no changes yet. The changes that are left to be made are in issue #151. Outside of this issue, I see no more pending changing left for this issue, so I have closed it.
