### ISSUE TITLE
implicit semantic is not clear enough

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#65]
`implicit` is not an adaptor as the other as it is a class not a function.

I would like to have in the documentation a more comprehensive description of how `implicit` behaves. 

Is something like that

```c++
implicit<TC>(xs....).operator X() <==> TC<X>(xs...).operator X()
```

**Comment by pfultz2** [comment]
I don't know a clean way to show it yet, since it relies on the implict conversion operator. I need to think about that.

**Comment by pfultz2** [comment]
> implicit is not an adaptor as the other as it is a class not a function.

It is a StaticFunctionAdaptor as explained [here](http://fit.readthedocs.org/en/latest/overview/index.html#static-function-adaptor), so it is only a class(the `static_` adaptor is like this too). However, it takes a template instead of a class. Perhaps, I should move the static function adaptors to their own section.

**Comment by viboes** [comment]
As you have section for each king of Adaptors, Functions, maybe you can add directly Static Function Adaptors

**Comment by pfultz2** [comment]
Ok I added a semantic section to make this clearer.
